# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#5AACA0"

# Main text color
theme[main_fg]="#1A3344"

# Title color for boxes
theme[title]="#1A3344"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#1299CA"

# Background color of selected item in processes box
theme[selected_bg]="#2A4A58"

# Foreground color of selected item in processes box
theme[selected_fg]="#1299CA"

# Color of inactive/disabled text
theme[inactive_fg]="#2A4A58"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#1A3344"

# Background color of the percentage meters
theme[meter_bg]="#2A4A58"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#1A3344"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#5A9EC8"
theme[mem_box]="#4EC85A"
theme[net_box]="#C85A50"
theme[proc_box]="#1299CA"

# Box divider line and small boxes line color
theme[div_line]="#2A4A58"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#4EC85A"
theme[temp_mid]="#A08020"
theme[temp_end]="#C85A50"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#3AB0B4"
theme[cpu_mid]="#2A8FC4"
theme[cpu_end]="#5A9EC8"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#5A9EC8"
theme[free_mid]="#2A8FC4"
theme[free_end]="#3AB0B4"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#2A8FC4"
theme[cached_mid]="#3AB0B4"
theme[cached_end]="#5A9EC8"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#A08020"
theme[available_mid]="#C85A50"
theme[available_end]="#C85A50"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#4EC85A"
theme[used_mid]="#3AB0B4"
theme[used_end]="#2A8FC4"

# Download graph colors (Peach -> Red)
theme[download_start]="#A08020"
theme[download_mid]="#C85A50"
theme[download_end]="#C85A50"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#4EC85A"
theme[upload_mid]="#3AB0B4"
theme[upload_end]="#2A8FC4"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#3AB0B4"
theme[process_mid]="#2A8FC4"
theme[process_end]="#5A9EC8"
