accent = "#1299CA"
cursor = "#1A3344"

foreground = "#1A3344"
background = "#5AACA0"

selection_foreground = "#5AACA0"
selection_background = "#1299CA"

color0  = "#1A3344"
color1  = "#C85A50"
color2  = "#4EC85A"
color3  = "#A08020"
color4  = "#2A8FC4"
color5  = "#5A9EC8"
color6  = "#3AB0B4"
color7  = "#C8E4E0"

color8  = "#2A4A58"
color9  = "#E86A60"
color10 = "#5ED85A"
color11 = "#E8C040"
color12 = "#3AA0D4"
color13 = "#6AB0D8"
color14 = "#4AC0C4"
color15 = "#E0F4F2"
