background = #5AACA0
foreground = #1A3344
cursor-color = #1A3344
selection-background = #1299CA
selection-foreground = #5AACA0

palette = 0=#1A3344
palette = 1=#C85A50
palette = 2=#4EC85A
palette = 3=#A08020
palette = 4=#2A8FC4
palette = 5=#5A9EC8
palette = 6=#3AB0B4
palette = 7=#C8E4E0
palette = 8=#2A4A58
palette = 9=#E86A60
palette = 10=#5ED85A
palette = 11=#E8C040
palette = 12=#3AA0D4
palette = 13=#6AB0D8
palette = 14=#4AC0C4
palette = 15=#E0F4F2
